services:
  discollama:
    image: endrence/discollama:latest
    restart: always
    command: ['--redis-host', 'redis']
    environment:
      - DISCORD_TOKEN
      - OLLAMA_HOST
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=mike/discollama

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - /data
    ports:
      - 6379
